services: 

  postgres:
    image: postgres:15
    container_name: url-shortener-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # ports:
    #   - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    container_name: url-shortener-backend
    ports: 
      - 8000:8000
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres
    restart: unless-stopped
  
  frontend:
    build: ./frontend
    container_name: url-shortener-frontend
    ports:
      - 80:80
    depends_on:
      - backend
    restart: unless-stopped
volumes:
  postgres_data:


      
